<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nigel Gebodh">
<meta name="dcterms.date" content="2024-10-24">

<title>Why Does My LLM Have A Temperature?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="LLM_temp_files/libs/clipboard/clipboard.min.js"></script>
<script src="LLM_temp_files/libs/quarto-html/quarto.js"></script>
<script src="LLM_temp_files/libs/quarto-html/popper.min.js"></script>
<script src="LLM_temp_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LLM_temp_files/libs/quarto-html/anchor.min.js"></script>
<link href="LLM_temp_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LLM_temp_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LLM_temp_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LLM_temp_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LLM_temp_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">

<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why Does My LLM Have A Temperature?</h1>
<p class="subtitle lead">Understanding the temperature parameter in LLMs</p>
  <div class="quarto-categories">
    <div class="quarto-category">LLM</div>
    <div class="quarto-category">ML</div>
    <div class="quarto-category">Deep Learning</div>
    <div class="quarto-category">Math</div>
  </div>
  </div>



<div class="quarto-title-meta column-page">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nigel Gebodh </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 24, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div id="cell-1" class="cell" data-execution_count="367">
<div class="cell-output cell-output-display">

<div id="non-scrollable-output"></div>
</div>
</div>
<style> 
      /* The . with the boxed represents that it is a class */
      .boxed {
        background: #e6fffe; /* C5F7F8 E5FAFA E1FCFC  #ecfffe #E5FAFA*/
        color: #0b3357; /* gray navy*/
        border: 3px solid #2980B9;
        margin: 10% auto;
        width: 95%;
        height: 95%;
        padding: 20px;
        border-radius: 20px;
      }
    </style>
<p>If you’ve interacted with AI assistants of LLMs (Large Language Model) in the past you may have noticed a parameter called <strong>Temperature</strong>. <br><br> Here we’ll look at how temperature affects LLM outputs, its calculation, and some examples of varying temperature values.</p>
<section id="what-exactly-is-an-llms-temperature" class="level2">
<h2 class="anchored" data-anchor-id="what-exactly-is-an-llms-temperature">What exactly is an LLM’s Temperature?</h2>
<div class="boxed">
<p><strong>LLM Temperature</strong> is a parameter that controls the probability distribution of the predicted next words of an LLM. It introduces some randomness or variety to the LLM’s outputs by changing the liklihood of the next words being selected. It can influence the LLM’s outputs to be either more deterministic (predictable) or more stochastic (random). Parameters like temperature are used to simulate or mimic the inherent variation in human language generation.</p>
<p>In production temperature values can typically range between 0-2+.</p>
<ul>
<li><p><strong>Lower temperature</strong> values (&lt;1) can lead to more deterministic or predictable LLM outputs, referred to as making the LLM more “precise”.</p></li>
<li><p><strong>Temperature of 1</strong> defaults to the LLMs inherent word distribution learned during training. It’s just the unaltered softmax function (more on this later).</p></li>
<li><p><strong>Higher temperature</strong> values (&gt;1) can lead to more stochastic or random and varied LLM outputs, referred to as making the LLM more “creative”.</p></li>
</ul>
</div>
<p>When the temperature value is set to 0, most systems trigger greedy sampling for next word predictions, which simply takes the word with the highest probability in the vocabulary (<em>Note</em>: other sampling methods exist for text generation see <a href="https://huggingface.co/docs/transformers/en/generation_strategies">here</a>). In some cases (if not properly controlled) the temperature value is <strong>too high (&gt;&gt;2)</strong> or <strong>too low (=0)</strong> this can trigger degenerate behavior like repetitive loops or LLM hallucinations.</p>
<p><strong>Hallucinations</strong> (metaphorically related to human hallucinations where a person may see or hear things that are not physically there) are LLM outputs that sometimes read as plausible but are factually wrong, or incoherent nonsensical text. It should be noted that temperature values between 0-2 do not prevent LLM hallucinations, they simply introduce randomness/diversity into the LLM outputs. Strategies like RAG (Retrieval Augmented Generation), CoT (Chain of Thought) etc. can be used to reduce hallucinations.</p>
<p><br> <img src="LLM_temp_scale.gif" alt="Changing the temperature scale of the LLM adjusts the probability distribution of words predicted by the LLM" width="65%" height="auto" style="display: block; margin-left: auto; margin-right: auto; border: none;"> <br></p>
</section>
<section id="llm-recap" class="level2">
<h2 class="anchored" data-anchor-id="llm-recap">LLM Recap</h2>
<p>Before diving deeper into the math let’s side track to rember how LLM calculations work (<em>overly simplified</em>). <br> <br> LLMs can be thought of as next word prediction machines, where predications are made from what they’ve learned during training. <br> Input text to the LLM are:</p>
<ul>
<li><strong>Tokenized</strong> words are converted to numeric representations (a look up table)</li>
<li><strong>Encoded</strong> to vector representaitons</li>
<li><strong>Decoded</strong> using a decoder model which produces <strong>logits</strong></li>
<li><strong>Softmax transformation</strong> is then applied to the logits to create a probability distribution</li>
<li><strong>Word selection</strong> then takes place from the probability distribution</li>
</ul>
<p>[INSERT IMAGE OF LLM]</p>
</section>
<section id="the-math" class="level2">
<h2 class="anchored" data-anchor-id="the-math">The Math</h2>
<section id="the-softmax-function-and-temperature" class="level3">
<h3 class="anchored" data-anchor-id="the-softmax-function-and-temperature">The Softmax Function and Temperature</h3>
<p>The <strong>softmax function</strong> is a widely used mathematical transformation that takes a set of values and transforms them into a set of probabilities that sum to 1. In NLP (Natural Language Processing) the softmax function takes the logits produced by LLMs and creates a scaled distribution of next words. <br> The softmax function is defined as:</p>
<p><span class="math display">\[
\mathbf{Softmax}(x_i) = \frac{ \textcolor{None}{  e^{x_i} } }{ \textcolor{None}{ \sum_{j=1}^{N} e^{x_j}  } }
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> value of each input</li>
<li><span class="math inline">\(e^{x_i}\)</span> is the exponentiation of the value of each input (Euler’s number: <span class="math inline">\(e\)</span> ~ <span class="math inline">\(2.71828\)</span>)</li>
<li><span class="math inline">\(\sum_{j=1}^{N} e^{x_j}\)</span> is the sum of all the exponentiated (<span class="math inline">\(e\)</span>) inputs (<span class="math inline">\(x\)</span>)</li>
</ul>
<p>All this means is take each value of <span class="math inline">\(x\)</span>, raise <span class="math inline">\(e\)</span> to that value and divide it by the sum of <span class="math inline">\(e\)</span> raised to each value of <span class="math inline">\(x\)</span>.</p>
<p>The <strong>Temperature (T)</strong> parameters is a simple modification to the softmax function that adjusts the inputs:</p>
<p><span class="math display">\[
\mathbf{Softmax}(x_i) = \frac{ \textcolor{None}{  e^{  \frac{x_i}{ \textcolor{red}{T} }     }}}
                             { \textcolor{None}{ \sum_{j=1}^{N} e^{   \frac{x_j}{ \textcolor{red}{T} }    }  } }
\]</span></p>
<p>The term “Temperature” is borrowed from the field of physics. It comes from its relationship to the <a href="https://en.wikipedia.org/wiki/Maxwell%E2%80%93Boltzmann_distribution">Boltzman distribution</a>, which describes how energy states change with temperature. Early usage of the term “temperature” in machine learning came from <a href="https://www.sciencedirect.com/science/article/pii/S0364021385800124">Ackley and colleagues in 1985</a>.</p>
<p><br></p>
<section id="examples" class="level4">
<h4 class="anchored" data-anchor-id="examples">Examples</h4>
<section id="example-1---simple-softmax-transformation-without-temperature" class="level5">
<h5 class="anchored" data-anchor-id="example-1---simple-softmax-transformation-without-temperature">Example 1 - Simple Softmax Transformation without Temperature</h5>
<details>
<summary>
Example
</summary>
<p>Given a list of numbers calculate their softmax probabilities. <br></p>
<ul>
<li><span class="math inline">\(list = [2.0, 4.0, 3.0]\)</span></li>
</ul>
<p><br></p>
<p><strong>By Hand:</strong></p>
<div id="cell-6" class="cell" data-execution_count="290">
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \begin{align}
x &amp;= [2.0, 4.0, 3.0] \\
\\
e^x &amp;= [e^{2.0}, e^{4.0}, e^{3.0}] \\
\\
\sum_{i=1}^{n = 3}  e^x &amp;= e^{2.0} + e^{4.0} + e^{3.0} \\
\\
\mathbf{\text{Softmax}(x)} &amp;= \left[\frac{e^{2.0}}{e^{2.0} + e^{4.0} + e^{3.0}}, \frac{e^{4.0}}{e^{2.0} + e^{4.0} + e^{3.0}}, \frac{e^{3.0}}{e^{2.0} + e^{4.0} + e^{3.0}}\right] \\
\\
&amp;= [0.0900, 0.6652, 0.2447]\\
\end{align}\)</span></p>
</div>
</div>
<p><strong>Using Python:</strong></p>
<div id="cell-8" class="cell" data-execution_count="291">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculating Softmax</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#1) Using Our Function</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Define a softmax function</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> my_softmax(input_vector):</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.exp(input_vector)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> e <span class="op">/</span> e.<span class="bu">sum</span>()</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>list_in <span class="op">=</span> [<span class="fl">2.0</span>, <span class="fl">4.0</span>, <span class="fl">3.0</span>]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>my_softmax(list_in)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">#2) Using PyTorch Function</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert list to torch tensor</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>list_in_torch <span class="op">=</span> torch.tensor(list_in)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities (using Pytorch) are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>F<span class="sc">.</span>softmax(list_in_torch, dim<span class="op">=</span><span class="dv">0</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
The softmax probabilities are: 
 [0.09003057 0.66524096 0.24472847]

The softmax probabilities (using Pytorch) are: 
 tensor([0.0900, 0.6652, 0.2447])</code></pre>
</div>
</div>
</details>

</section>
<section id="example-2---simple-softmax-transformation-with-varying-temperatures" class="level5">
<h5 class="anchored" data-anchor-id="example-2---simple-softmax-transformation-with-varying-temperatures">Example 2 - Simple Softmax Transformation with Varying Temperatures</h5>
<details>
<summary>
Example
</summary>
<p>Given a list of numbers calculate their softmax probabilities at termperatures of T=[0.5, 1, 2] <br></p>
<p><br></p>
<ul>
<li><span class="math inline">\(list = [2.0, 4.0, 3.0]\)</span></li>
</ul>
<p><br></p>
<details>
<summary>
<strong>Temperature: 0.5</strong>
</summary>
<p><strong>By Hand:</strong></p>
<div id="cell-13" class="cell" data-execution_count="292">
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \begin{align}
\text{Given:} \\
x &amp;= [2.0, 4.0, 3.0] \\
\color{red}T &amp;= 0.5 \\
\\
\\
\text{Softmax}(x_{i=1:3},{\color{red}T}) &amp;= \frac{\color{steelblue}{       e^{\frac{x_i}{ \color{red}{T} }} }      } {\color{purple}{         \sum_{j=1}^{N}{ e^{\frac{x_j}{  \color{red}{T}  }}           }   } } \\
\\
\\
\text{The numerator:} \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{2.0/\color{red}T}}, \color{steelblue}{e^{4.0/\color{red}T}}, \color{steelblue}{e^{3.0/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}0.5} &amp;= \left[\color{steelblue}{e^{2.0/\color{red}0.5}}, \color{steelblue}{e^{4.0/\color{red}0.5}}, \color{steelblue}{e^{3.0/\color{red}0.5}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}0.5} &amp;= \left[\color{steelblue}{e^{{4}}}, \color{steelblue}{e^{{8}}}, \color{steelblue}{e^{{6}}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}0.5} &amp;= \left[\color{steelblue}{54.6}, \color{steelblue}{2.98e+03}, \color{steelblue}{403}\color{None}\right] \\
\\
\text{The denominator:} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{x_1/\color{red}T}} + \color{purple}{e^{x_2/\color{red}T}} + \color{purple}{e^{x_3/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{2.0/\color{red}T}} + \color{purple}{e^{4.0/\color{red}T}} + \color{purple}{e^{3.0/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}0.5} &amp;= \color{purple}{e^{2.0/\color{red}0.5}} + \color{purple}{e^{4.0/\color{red}0.5}} + \color{purple}{e^{3.0/\color{red}0.5}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}0.5} &amp;= \color{purple}{e^{{4}}} + \color{purple}{e^{{8}}} + \color{purple}{e^{{6}}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}0.5} &amp;= \color{purple}{54.6} + \color{purple}{2.98e+03} + \color{purple}{403} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}0.5} &amp;= \color{purple}3.44e+03 \\
\\
\\
\text{Combine all:} \\
\text{Softmax}(x_{i=1:3},{\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{x_1/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }, \frac{\color{steelblue}e^{x_2/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }, \frac{\color{steelblue}e^{x_3/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }\right] \\\\
\text{Softmax}(x, {\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{2.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }, \frac{\color{steelblue}e^{4.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }, \frac{\color{steelblue}e^{3.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }\right] \\
\\
\text{softmax}(x, {\color{red}0.5}) &amp;= \left[\frac{  \color{steelblue} e^{2.0/\color{red}0.5}} {  \color{purple} e^{2.0/\color{red}0.5} + e^{4.0/\color{red}0.5} + e^{3.0/\color{red}0.5}    }, \frac{  \color{steelblue} e^{4.0/\color{red}0.5}} {  \color{purple} e^{2.0/\color{red}0.5} + e^{4.0/\color{red}0.5} + e^{3.0/\color{red}0.5}    }, \frac{  \color{steelblue} e^{3.0/\color{red}0.5}} {  \color{purple} e^{2.0/\color{red}0.5} + e^{4.0/\color{red}0.5} + e^{3.0/\color{red}0.5}    }\right] \\
\\
\text{softmax}(x, {\color{red}0.5}) &amp;= \left[\frac{  \color{steelblue}  e^{ 4.0 }} {  \color{purple} e^{4.0 } + e^{8.0 } + e^{6.0 }    }, \frac{  \color{steelblue}  e^{ 8.0 }} {  \color{purple} e^{4.0 } + e^{8.0 } + e^{6.0 }    }, \frac{  \color{steelblue}  e^{ 6.0 }} {  \color{purple} e^{4.0 } + e^{8.0 } + e^{6.0 }    }\right] \\
\\
\text{softmax}(x, {\color{red}0.5}) &amp;= \left[\frac{ \color{steelblue}  { 54.6 } } {  \color{purple} 54.6 + 2.98e+03 + 403    }, \frac{ \color{steelblue}  { 2.98e+03 } } {  \color{purple} 54.6 + 2.98e+03 + 403    }, \frac{ \color{steelblue}  { 403 } } {  \color{purple} 54.6 + 2.98e+03 + 403    }\right] \\
\\
\text{softmax}(x, {\color{red}0.5}) &amp;= \left[\frac{ \color{steelblue}{ 54.6 } } {  \color{purple} 3.44e+03    }, \frac{ \color{steelblue}{ 2.98e+03 } } {  \color{purple} 3.44e+03    }, \frac{ \color{steelblue}{ 403 } } {  \color{purple} 3.44e+03    }\right] \\
\\
\\
\text{softmax}(x, {\color{red}0.5})&amp;= [0.0159, 0.867, 0.117] \
\\
\text{Probabilities}&amp;= [0.0159, 0.867, 0.117]
\end{align}\)</span></p>
</div>
</div>
<p><strong>Using Python:</strong></p>
<div id="cell-15" class="cell" data-execution_count="293">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculating Softmax</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#1) Using Our Function</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Define a softmax function with temperature</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> my_softmax(input_vector, Temp<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.exp(np.divide(input_vector,Temp))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> e <span class="op">/</span> e.<span class="bu">sum</span>()</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>Temp <span class="op">=</span><span class="fl">0.5</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>list_in <span class="op">=</span> [<span class="fl">2.0</span>, <span class="fl">4.0</span>, <span class="fl">3.0</span>]</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities at a Temp = </span><span class="sc">{</span>Temp<span class="sc">}</span><span class="ss"> are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>my_softmax(list_in, Temp<span class="op">=</span>Temp)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co">#2) Using PyTorch Function</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert list to torch tensor</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>list_in_torch <span class="op">=</span> torch.tensor(list_in)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply temperature scaling </span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>scaled_logits <span class="op">=</span> list_in_torch <span class="op">/</span> Temp</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities (using Pytorch) are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>F<span class="sc">.</span>softmax(scaled_logits, dim<span class="op">=</span><span class="dv">0</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
The softmax probabilities at a Temp = 0.5 are: 
 [0.01587624 0.86681333 0.11731043]

The softmax probabilities (using Pytorch) are: 
 tensor([0.0159, 0.8668, 0.1173])</code></pre>
</div>
</div>
</details>
<details>
<summary>
<strong>Temperature: 1.0</strong>
</summary>
<p><strong>By Hand:</strong></p>
<div id="cell-17" class="cell" data-execution_count="294">
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \begin{align}
\text{Given:} \\
x &amp;= [2.0, 4.0, 3.0] \\
\color{red}T &amp;= 1.0 \\
\\
\\
\text{Softmax}(x_{i=1:3},{\color{red}T}) &amp;= \frac{\color{steelblue}{       e^{\frac{x_i}{ \color{red}{T} }} }      } {\color{purple}{         \sum_{j=1}^{N}{ e^{\frac{x_j}{  \color{red}{T}  }}           }   } } \\
\\
\\
\text{The numerator:} \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{2.0/\color{red}T}}, \color{steelblue}{e^{4.0/\color{red}T}}, \color{steelblue}{e^{3.0/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}1.0} &amp;= \left[\color{steelblue}{e^{2.0/\color{red}1.0}}, \color{steelblue}{e^{4.0/\color{red}1.0}}, \color{steelblue}{e^{3.0/\color{red}1.0}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}1.0} &amp;= \left[\color{steelblue}{e^{{2}}}, \color{steelblue}{e^{{4}}}, \color{steelblue}{e^{{3}}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}1.0} &amp;= \left[\color{steelblue}{7.39}, \color{steelblue}{54.6}, \color{steelblue}{20.1}\color{None}\right] \\
\\
\text{The denominator:} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{x_1/\color{red}T}} + \color{purple}{e^{x_2/\color{red}T}} + \color{purple}{e^{x_3/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{2.0/\color{red}T}} + \color{purple}{e^{4.0/\color{red}T}} + \color{purple}{e^{3.0/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}1.0} &amp;= \color{purple}{e^{2.0/\color{red}1.0}} + \color{purple}{e^{4.0/\color{red}1.0}} + \color{purple}{e^{3.0/\color{red}1.0}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}1.0} &amp;= \color{purple}{e^{{2}}} + \color{purple}{e^{{4}}} + \color{purple}{e^{{3}}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}1.0} &amp;= \color{purple}{7.39} + \color{purple}{54.6} + \color{purple}{20.1} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}1.0} &amp;= \color{purple}82.1 \\
\\
\\
\text{Combine all:} \\
\text{Softmax}(x_{i=1:3},{\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{x_1/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }, \frac{\color{steelblue}e^{x_2/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }, \frac{\color{steelblue}e^{x_3/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }\right] \\\\
\text{Softmax}(x, {\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{2.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }, \frac{\color{steelblue}e^{4.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }, \frac{\color{steelblue}e^{3.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{  \color{steelblue} e^{2.0/\color{red}1.0}} {  \color{purple} e^{2.0/\color{red}1.0} + e^{4.0/\color{red}1.0} + e^{3.0/\color{red}1.0}    }, \frac{  \color{steelblue} e^{4.0/\color{red}1.0}} {  \color{purple} e^{2.0/\color{red}1.0} + e^{4.0/\color{red}1.0} + e^{3.0/\color{red}1.0}    }, \frac{  \color{steelblue} e^{3.0/\color{red}1.0}} {  \color{purple} e^{2.0/\color{red}1.0} + e^{4.0/\color{red}1.0} + e^{3.0/\color{red}1.0}    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{  \color{steelblue}  e^{ 2.0 }} {  \color{purple} e^{2.0 } + e^{4.0 } + e^{3.0 }    }, \frac{  \color{steelblue}  e^{ 4.0 }} {  \color{purple} e^{2.0 } + e^{4.0 } + e^{3.0 }    }, \frac{  \color{steelblue}  e^{ 3.0 }} {  \color{purple} e^{2.0 } + e^{4.0 } + e^{3.0 }    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{ \color{steelblue}  { 7.39 } } {  \color{purple} 7.39 + 54.6 + 20.1    }, \frac{ \color{steelblue}  { 54.6 } } {  \color{purple} 7.39 + 54.6 + 20.1    }, \frac{ \color{steelblue}  { 20.1 } } {  \color{purple} 7.39 + 54.6 + 20.1    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{ \color{steelblue}{ 7.39 } } {  \color{purple} 82.1    }, \frac{ \color{steelblue}{ 54.6 } } {  \color{purple} 82.1    }, \frac{ \color{steelblue}{ 20.1 } } {  \color{purple} 82.1    }\right] \\
\\
\\
\text{softmax}(x, {\color{red}1.0})&amp;= [0.09, 0.665, 0.245] \
\\
\text{Probabilities}&amp;= [0.09, 0.665, 0.245]
\end{align}\)</span></p>
</div>
</div>
<p><strong>Using Python:</strong></p>
<div id="cell-19" class="cell" data-execution_count="295">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculating Softmax</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#1) Using Our Function</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Define a softmax function with temperature</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> my_softmax(input_vector, Temp<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.exp(np.divide(input_vector,Temp))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> e <span class="op">/</span> e.<span class="bu">sum</span>()</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>Temp <span class="op">=</span><span class="fl">1.0</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>list_in <span class="op">=</span> [<span class="fl">2.0</span>, <span class="fl">4.0</span>, <span class="fl">3.0</span>]</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities at a Temp = </span><span class="sc">{</span>Temp<span class="sc">}</span><span class="ss"> are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>my_softmax(list_in, Temp<span class="op">=</span>Temp)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co">#2) Using PyTorch Function</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert list to torch tensor</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>list_in_torch <span class="op">=</span> torch.tensor(list_in)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply temperature scaling </span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>scaled_logits <span class="op">=</span> list_in_torch <span class="op">/</span> Temp</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities (using Pytorch) are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>F<span class="sc">.</span>softmax(scaled_logits, dim<span class="op">=</span><span class="dv">0</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
The softmax probabilities at a Temp = 1.0 are: 
 [0.09003057 0.66524096 0.24472847]

The softmax probabilities (using Pytorch) are: 
 tensor([0.0900, 0.6652, 0.2447])</code></pre>
</div>
</div>
</details>
<details>
<summary>
<strong>Temperature: 2.0</strong>
</summary>
<p><strong>By Hand:</strong></p>
<div id="cell-21" class="cell" data-execution_count="296">
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \begin{align}
\text{Given:} \\
x &amp;= [2.0, 4.0, 3.0] \\
\color{red}T &amp;= 2.0 \\
\\
\\
\text{Softmax}(x_{i=1:3},{\color{red}T}) &amp;= \frac{\color{steelblue}{       e^{\frac{x_i}{ \color{red}{T} }} }      } {\color{purple}{         \sum_{j=1}^{N}{ e^{\frac{x_j}{  \color{red}{T}  }}           }   } } \\
\\
\\
\text{The numerator:} \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{2.0/\color{red}T}}, \color{steelblue}{e^{4.0/\color{red}T}}, \color{steelblue}{e^{3.0/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}2.0} &amp;= \left[\color{steelblue}{e^{2.0/\color{red}2.0}}, \color{steelblue}{e^{4.0/\color{red}2.0}}, \color{steelblue}{e^{3.0/\color{red}2.0}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}2.0} &amp;= \left[\color{steelblue}{e^{{1}}}, \color{steelblue}{e^{{2}}}, \color{steelblue}{e^{{1.5}}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}2.0} &amp;= \left[\color{steelblue}{2.72}, \color{steelblue}{7.39}, \color{steelblue}{4.48}\color{None}\right] \\
\\
\text{The denominator:} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{x_1/\color{red}T}} + \color{purple}{e^{x_2/\color{red}T}} + \color{purple}{e^{x_3/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{2.0/\color{red}T}} + \color{purple}{e^{4.0/\color{red}T}} + \color{purple}{e^{3.0/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}2.0} &amp;= \color{purple}{e^{2.0/\color{red}2.0}} + \color{purple}{e^{4.0/\color{red}2.0}} + \color{purple}{e^{3.0/\color{red}2.0}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}2.0} &amp;= \color{purple}{e^{{1}}} + \color{purple}{e^{{2}}} + \color{purple}{e^{{1.5}}} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}2.0} &amp;= \color{purple}{2.72} + \color{purple}{7.39} + \color{purple}{4.48} \\
\color{purple}\sum_{j=1}^{N=3} e^{x_j/\color{red}2.0} &amp;= \color{purple}14.6 \\
\\
\\
\text{Combine all:} \\
\text{Softmax}(x_{i=1:3},{\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{x_1/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }, \frac{\color{steelblue}e^{x_2/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }, \frac{\color{steelblue}e^{x_3/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T}     }\right] \\\\
\text{Softmax}(x, {\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{2.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }, \frac{\color{steelblue}e^{4.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }, \frac{\color{steelblue}e^{3.0/\color{red}T}} {  \color{purple} e^{2.0/\color{red}T} + e^{4.0/\color{red}T} + e^{3.0/\color{red}T}    }\right] \\
\\
\text{softmax}(x, {\color{red}2.0}) &amp;= \left[\frac{  \color{steelblue} e^{2.0/\color{red}2.0}} {  \color{purple} e^{2.0/\color{red}2.0} + e^{4.0/\color{red}2.0} + e^{3.0/\color{red}2.0}    }, \frac{  \color{steelblue} e^{4.0/\color{red}2.0}} {  \color{purple} e^{2.0/\color{red}2.0} + e^{4.0/\color{red}2.0} + e^{3.0/\color{red}2.0}    }, \frac{  \color{steelblue} e^{3.0/\color{red}2.0}} {  \color{purple} e^{2.0/\color{red}2.0} + e^{4.0/\color{red}2.0} + e^{3.0/\color{red}2.0}    }\right] \\
\\
\text{softmax}(x, {\color{red}2.0}) &amp;= \left[\frac{  \color{steelblue}  e^{ 1.0 }} {  \color{purple} e^{1.0 } + e^{2.0 } + e^{1.5 }    }, \frac{  \color{steelblue}  e^{ 2.0 }} {  \color{purple} e^{1.0 } + e^{2.0 } + e^{1.5 }    }, \frac{  \color{steelblue}  e^{ 1.5 }} {  \color{purple} e^{1.0 } + e^{2.0 } + e^{1.5 }    }\right] \\
\\
\text{softmax}(x, {\color{red}2.0}) &amp;= \left[\frac{ \color{steelblue}  { 2.72 } } {  \color{purple} 2.72 + 7.39 + 4.48    }, \frac{ \color{steelblue}  { 7.39 } } {  \color{purple} 2.72 + 7.39 + 4.48    }, \frac{ \color{steelblue}  { 4.48 } } {  \color{purple} 2.72 + 7.39 + 4.48    }\right] \\
\\
\text{softmax}(x, {\color{red}2.0}) &amp;= \left[\frac{ \color{steelblue}{ 2.72 } } {  \color{purple} 14.6    }, \frac{ \color{steelblue}{ 7.39 } } {  \color{purple} 14.6    }, \frac{ \color{steelblue}{ 4.48 } } {  \color{purple} 14.6    }\right] \\
\\
\\
\text{softmax}(x, {\color{red}2.0})&amp;= [0.186, 0.506, 0.307] \
\\
\text{Probabilities}&amp;= [0.186, 0.506, 0.307]
\end{align}\)</span></p>
</div>
</div>
<p><strong>Using Python:</strong></p>
<div id="cell-23" class="cell" data-execution_count="297">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculating Softmax</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#1) Using Our Function</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Define a softmax function with temperature</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> my_softmax(input_vector, Temp<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.exp(np.divide(input_vector,Temp))</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> e <span class="op">/</span> e.<span class="bu">sum</span>()</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>Temp <span class="op">=</span><span class="fl">2.0</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>list_in <span class="op">=</span> [<span class="fl">2.0</span>, <span class="fl">4.0</span>, <span class="fl">3.0</span>]</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities at a Temp = </span><span class="sc">{</span>Temp<span class="sc">}</span><span class="ss"> are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>my_softmax(list_in, Temp<span class="op">=</span>Temp)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="co">#2) Using PyTorch Function</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert list to torch tensor</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>list_in_torch <span class="op">=</span> torch.tensor(list_in)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply temperature scaling </span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>scaled_logits <span class="op">=</span> list_in_torch <span class="op">/</span> Temp</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The softmax probabilities (using Pytorch) are: </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>F<span class="sc">.</span>softmax(scaled_logits, dim<span class="op">=</span><span class="dv">0</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
The softmax probabilities at a Temp = 2.0 are: 
 [0.18632372 0.50648039 0.30719589]

The softmax probabilities (using Pytorch) are: 
 tensor([0.1863, 0.5065, 0.3072])</code></pre>
</div>
</div>
</details>
</details>

</section>
<section id="example-3---llm-output-softmax-transformation-with-varying-temperatures" class="level5">
<h5 class="anchored" data-anchor-id="example-3---llm-output-softmax-transformation-with-varying-temperatures">Example 3 - LLM Output Softmax Transformation with Varying Temperatures</h5>
<details>
<summary>
Example
</summary>
<p>Given a list of logit outputs from a LLM, find the most probable word and its probability. <br> Assume the that LLM only knows 5 words (LLM vocabularies typically contain thousands of words). <br> Calculate the probabilities for temperatures of 1.0 and 100.0</p>
<ul>
<li><span class="math inline">\(index = [0, 1, 2, 3, 4]\)</span></li>
<li><span class="math inline">\(words = [ceiling, floor, mat, car, grass]\)</span></li>
<li><span class="math inline">\(logits = [-49.82, -46.40, -45.25, -47.30, -48.32]\)</span></li>
</ul>
<p><br></p>
<details>
<summary>
<strong>Temperature: 1.0</strong>
</summary>
<p><strong>By Hand:</strong></p>
<div id="cell-28" class="cell" data-execution_count="370">
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \begin{align}
\text{Given:} \\
x &amp;= [-49.82, -46.4, -45.25, -47.3, -48.32] \\
\color{red}T &amp;= 1.0 \\
\\
\\
\text{Softmax}(x_{i=1:5},{\color{red}T}) &amp;= \frac{\color{steelblue}{       e^{\frac{x_i}{ \color{red}{T} }} }      } {\color{purple}{         \sum_{j=1}^{N}{ e^{\frac{x_j}{  \color{red}{T}  }}           }   } } \\
\\
\\
\text{The numerator:} \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}, \color{steelblue}{e^{x_4/\color{red}T}}, \color{steelblue}{e^{x_5/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{-49.82/\color{red}T}}, \color{steelblue}{e^{-46.4/\color{red}T}}, \color{steelblue}{e^{-45.25/\color{red}T}}, \color{steelblue}{e^{-47.3/\color{red}T}}, \color{steelblue}{e^{-48.32/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}1.0} &amp;= \left[\color{steelblue}{e^{-49.82/\color{red}1.0}}, \color{steelblue}{e^{-46.4/\color{red}1.0}}, \color{steelblue}{e^{-45.25/\color{red}1.0}}, \color{steelblue}{e^{-47.3/\color{red}1.0}}, \color{steelblue}{e^{-48.32/\color{red}1.0}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}1.0} &amp;= \left[\color{steelblue}{e^{{-49.82}}}, \color{steelblue}{e^{{-46.4}}}, \color{steelblue}{e^{{-45.25}}}, \color{steelblue}{e^{{-47.3}}}, \color{steelblue}{e^{{-48.32}}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}1.0} &amp;= \left[\color{steelblue}{2.309e-22}, \color{steelblue}{7.059e-21}, \color{steelblue}{2.229e-20}, \color{steelblue}{2.87e-21}, \color{steelblue}{1.035e-21}\color{None}\right] \\
\\
\text{The denominator:} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{x_1/\color{red}T}} + \color{purple}{e^{x_2/\color{red}T}} + \color{purple}{e^{x_3/\color{red}T}} + \color{purple}{e^{x_4/\color{red}T}} + \color{purple}{e^{x_5/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{-49.82/\color{red}T}} + \color{purple}{e^{-46.4/\color{red}T}} + \color{purple}{e^{-45.25/\color{red}T}} + \color{purple}{e^{-47.3/\color{red}T}} + \color{purple}{e^{-48.32/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}1.0} &amp;= \color{purple}{e^{-49.82/\color{red}1.0}} + \color{purple}{e^{-46.4/\color{red}1.0}} + \color{purple}{e^{-45.25/\color{red}1.0}} + \color{purple}{e^{-47.3/\color{red}1.0}} + \color{purple}{e^{-48.32/\color{red}1.0}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}1.0} &amp;= \color{purple}{e^{{-49.82}}} + \color{purple}{e^{{-46.4}}} + \color{purple}{e^{{-45.25}}} + \color{purple}{e^{{-47.3}}} + \color{purple}{e^{{-48.32}}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}1.0} &amp;= \color{purple}{2.309e-22} + \color{purple}{7.059e-21} + \color{purple}{2.229e-20} + \color{purple}{2.87e-21} + \color{purple}{1.035e-21} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}1.0} &amp;= \color{purple}3.349e-20 \\
\\
\\
\text{Combine all:} \\
\text{Softmax}(x_{i=1:5},{\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{x_1/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_2/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_3/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_4/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_5/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }\right] \\\\
\text{Softmax}(x, {\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{-49.82/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-46.4/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-45.25/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-47.3/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-48.32/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{  \color{steelblue} e^{-49.82/\color{red}1.0}} {  \color{purple} e^{-49.82/\color{red}1.0} + e^{-46.4/\color{red}1.0} + e^{-45.25/\color{red}1.0} + e^{-47.3/\color{red}1.0} + e^{-48.32/\color{red}1.0}    }, \frac{  \color{steelblue} e^{-46.4/\color{red}1.0}} {  \color{purple} e^{-49.82/\color{red}1.0} + e^{-46.4/\color{red}1.0} + e^{-45.25/\color{red}1.0} + e^{-47.3/\color{red}1.0} + e^{-48.32/\color{red}1.0}    }, \frac{  \color{steelblue} e^{-45.25/\color{red}1.0}} {  \color{purple} e^{-49.82/\color{red}1.0} + e^{-46.4/\color{red}1.0} + e^{-45.25/\color{red}1.0} + e^{-47.3/\color{red}1.0} + e^{-48.32/\color{red}1.0}    }, \frac{  \color{steelblue} e^{-47.3/\color{red}1.0}} {  \color{purple} e^{-49.82/\color{red}1.0} + e^{-46.4/\color{red}1.0} + e^{-45.25/\color{red}1.0} + e^{-47.3/\color{red}1.0} + e^{-48.32/\color{red}1.0}    }, \frac{  \color{steelblue} e^{-48.32/\color{red}1.0}} {  \color{purple} e^{-49.82/\color{red}1.0} + e^{-46.4/\color{red}1.0} + e^{-45.25/\color{red}1.0} + e^{-47.3/\color{red}1.0} + e^{-48.32/\color{red}1.0}    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{  \color{steelblue}  e^{ -49.82 }} {  \color{purple} e^{-49.82 } + e^{-46.4 } + e^{-45.25 } + e^{-47.3 } + e^{-48.32 }    }, \frac{  \color{steelblue}  e^{ -46.4 }} {  \color{purple} e^{-49.82 } + e^{-46.4 } + e^{-45.25 } + e^{-47.3 } + e^{-48.32 }    }, \frac{  \color{steelblue}  e^{ -45.25 }} {  \color{purple} e^{-49.82 } + e^{-46.4 } + e^{-45.25 } + e^{-47.3 } + e^{-48.32 }    }, \frac{  \color{steelblue}  e^{ -47.3 }} {  \color{purple} e^{-49.82 } + e^{-46.4 } + e^{-45.25 } + e^{-47.3 } + e^{-48.32 }    }, \frac{  \color{steelblue}  e^{ -48.32 }} {  \color{purple} e^{-49.82 } + e^{-46.4 } + e^{-45.25 } + e^{-47.3 } + e^{-48.32 }    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{ \color{steelblue}  { 2.309e-22 } } {  \color{purple} 2.309e-22 + 7.059e-21 + 2.229e-20 + 2.87e-21 + 1.035e-21    }, \frac{ \color{steelblue}  { 7.059e-21 } } {  \color{purple} 2.309e-22 + 7.059e-21 + 2.229e-20 + 2.87e-21 + 1.035e-21    }, \frac{ \color{steelblue}  { 2.229e-20 } } {  \color{purple} 2.309e-22 + 7.059e-21 + 2.229e-20 + 2.87e-21 + 1.035e-21    }, \frac{ \color{steelblue}  { 2.87e-21 } } {  \color{purple} 2.309e-22 + 7.059e-21 + 2.229e-20 + 2.87e-21 + 1.035e-21    }, \frac{ \color{steelblue}  { 1.035e-21 } } {  \color{purple} 2.309e-22 + 7.059e-21 + 2.229e-20 + 2.87e-21 + 1.035e-21    }\right] \\
\\
\text{softmax}(x, {\color{red}1.0}) &amp;= \left[\frac{ \color{steelblue}{ 2.309e-22 } } {  \color{purple} 3.349e-20    }, \frac{ \color{steelblue}{ 7.059e-21 } } {  \color{purple} 3.349e-20    }, \frac{ \color{steelblue}{ 2.229e-20 } } {  \color{purple} 3.349e-20    }, \frac{ \color{steelblue}{ 2.87e-21 } } {  \color{purple} 3.349e-20    }, \frac{ \color{steelblue}{ 1.035e-21 } } {  \color{purple} 3.349e-20    }\right] \\
\\
\\
\text{softmax}(x, {\color{red}1.0})&amp;= [0.006895, 0.2108, 0.6657, 0.0857, 0.0309] \
\\
\text{Probabilities}&amp;= [0.006895, 0.2108, 0.6657, 0.0857, 0.0309]
\end{align}\)</span></p>
</div>
</div>
<p><strong>Using Python:</strong></p>
<div id="cell-30" class="cell" data-execution_count="361">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example Softmax Calculation</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume for simplicity:</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># * The model only knows the 5 words listed below (it has a vocabulary of 5).</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Example model output</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>model_output_vals <span class="op">=</span> {<span class="st">"word_index"</span>:[i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>)],</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                <span class="st">"words"</span>:[<span class="st">"ceiling"</span>, <span class="st">"floor"</span>, <span class="st">"mat"</span>, <span class="st">"car"</span>, <span class="st">"grass"</span>], </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                <span class="st">"logits"</span>:[<span class="op">-</span><span class="fl">49.82</span>, <span class="op">-</span><span class="fl">46.40</span>, <span class="op">-</span><span class="fl">45.25</span>, <span class="op">-</span><span class="fl">47.30</span>, <span class="op">-</span><span class="fl">48.32</span>]}</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert the data to a DataFrame</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>model_output <span class="op">=</span> pd.DataFrame(model_output_vals)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Define a softmax function with temperature</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> my_softmax(input_vector, Temp<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.exp(np.divide(input_vector,Temp))</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> e <span class="op">/</span> e.<span class="bu">sum</span>()</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate the probabilities</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span>  my_softmax(model_output[<span class="st">"logits"</span>], Temp<span class="op">=</span>temp)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>model_output[<span class="st">"softmax_prob"</span>] <span class="op">=</span> probs </span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="co">#Select the most probable word</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>most_prob <span class="op">=</span> np.argmax(probs)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The index of the most probable word is: </span><span class="sc">{</span>most_prob<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="co">#Pull out the most probable word</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The most probable word is: </span><span class="sc">{</span> model_output[<span class="st">'words'</span>][most_prob] <span class="sc">}</span><span class="ss">"</span> \</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f" (Prob: </span><span class="sc">{</span>model_output[<span class="st">'softmax_prob'</span>][most_prob]<span class="sc">:.5f}</span><span class="ss">)"</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="co">#Style our table</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>cm <span class="op">=</span> sns.light_palette(<span class="st">"orange"</span>, as_cmap<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>s1 <span class="op">=</span> model_output</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>s1 <span class="op">=</span> s1.style.background_gradient(subset<span class="op">=</span>[<span class="st">"logits"</span>],cmap<span class="op">=</span>cm)</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>cm <span class="op">=</span> sns.light_palette(<span class="st">"green"</span>, as_cmap<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>s1.background_gradient(subset<span class="op">=</span>[<span class="st">"softmax_prob"</span>],cmap<span class="op">=</span>cm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
The index of the most probable word is: 2

The most probable word is: mat (Prob: 0.66571)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="361">
<style type="text/css">
#T_0b196_row0_col2 {
  background-color: #f3f0ee;
  color: #000000;
}
#T_0b196_row0_col3 {
  background-color: #ebf3eb;
  color: #000000;
}
#T_0b196_row1_col2 {
  background-color: #fcb83c;
  color: #000000;
}
#T_0b196_row1_col3 {
  background-color: #a2cfa2;
  color: #000000;
}
#T_0b196_row2_col2 {
  background-color: #ffa500;
  color: #000000;
}
#T_0b196_row2_col3 {
  background-color: #008000;
  color: #f1f1f1;
}
#T_0b196_row3_col2 {
  background-color: #fac76b;
  color: #000000;
}
#T_0b196_row3_col3 {
  background-color: #cfe5cf;
  color: #000000;
}
#T_0b196_row4_col2 {
  background-color: #f7d7a0;
  color: #000000;
}
#T_0b196_row4_col3 {
  background-color: #e2efe2;
  color: #000000;
}
</style>

<table id="T_0b196" data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_0b196_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">word_index</th>
<th id="T_0b196_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">words</th>
<th id="T_0b196_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">logits</th>
<th id="T_0b196_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">softmax_prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_0b196_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">0</td>
<td id="T_0b196_row0_col0" class="data row0 col0">0</td>
<td id="T_0b196_row0_col1" class="data row0 col1">ceiling</td>
<td id="T_0b196_row0_col2" class="data row0 col2">-49.820000</td>
<td id="T_0b196_row0_col3" class="data row0 col3">0.006895</td>
</tr>
<tr class="even">
<td id="T_0b196_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">1</td>
<td id="T_0b196_row1_col0" class="data row1 col0">1</td>
<td id="T_0b196_row1_col1" class="data row1 col1">floor</td>
<td id="T_0b196_row1_col2" class="data row1 col2">-46.400000</td>
<td id="T_0b196_row1_col3" class="data row1 col3">0.210789</td>
</tr>
<tr class="odd">
<td id="T_0b196_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">2</td>
<td id="T_0b196_row2_col0" class="data row2 col0">2</td>
<td id="T_0b196_row2_col1" class="data row2 col1">mat</td>
<td id="T_0b196_row2_col2" class="data row2 col2">-45.250000</td>
<td id="T_0b196_row2_col3" class="data row2 col3">0.665712</td>
</tr>
<tr class="even">
<td id="T_0b196_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">3</td>
<td id="T_0b196_row3_col0" class="data row3 col0">3</td>
<td id="T_0b196_row3_col1" class="data row3 col1">car</td>
<td id="T_0b196_row3_col2" class="data row3 col2">-47.300000</td>
<td id="T_0b196_row3_col3" class="data row3 col3">0.085700</td>
</tr>
<tr class="odd">
<td id="T_0b196_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">4</td>
<td id="T_0b196_row4_col0" class="data row4 col0">4</td>
<td id="T_0b196_row4_col1" class="data row4 col1">grass</td>
<td id="T_0b196_row4_col2" class="data row4 col2">-48.320000</td>
<td id="T_0b196_row4_col3" class="data row4 col3">0.030903</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-31" class="cell" data-execution_count="362">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-32" class="cell" data-execution_count="364">
<div class="cell-output cell-output-display cell-output-markdown">
<p>From the softmax probabilities we see that the most probable word is: <span style="color: green; font-weight: bold">mat</span> with a probability of : <span style="color: green; font-weight: bold">0.666</span></p>
</div>
</div>
</details>
<details>
<summary>
<strong>Temperature: 100.0</strong>
</summary>
<p><strong>By Hand:</strong></p>
<div id="cell-34" class="cell" data-execution_count="371">
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \begin{align}
\text{Given:} \\
x &amp;= [-49.82, -46.4, -45.25, -47.3, -48.32] \\
\color{red}T &amp;= 100.0 \\
\\
\\
\text{Softmax}(x_{i=1:5},{\color{red}T}) &amp;= \frac{\color{steelblue}{       e^{\frac{x_i}{ \color{red}{T} }} }      } {\color{purple}{         \sum_{j=1}^{N}{ e^{\frac{x_j}{  \color{red}{T}  }}           }   } } \\
\\
\\
\text{The numerator:} \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{x_1/\color{red}T}}, \color{steelblue}{e^{x_2/\color{red}T}}, \color{steelblue}{e^{x_3/\color{red}T}}, \color{steelblue}{e^{x_4/\color{red}T}}, \color{steelblue}{e^{x_5/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}T} &amp;= \left[\color{steelblue}{e^{-49.82/\color{red}T}}, \color{steelblue}{e^{-46.4/\color{red}T}}, \color{steelblue}{e^{-45.25/\color{red}T}}, \color{steelblue}{e^{-47.3/\color{red}T}}, \color{steelblue}{e^{-48.32/\color{red}T}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}100.0} &amp;= \left[\color{steelblue}{e^{-49.82/\color{red}100.0}}, \color{steelblue}{e^{-46.4/\color{red}100.0}}, \color{steelblue}{e^{-45.25/\color{red}100.0}}, \color{steelblue}{e^{-47.3/\color{red}100.0}}, \color{steelblue}{e^{-48.32/\color{red}100.0}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}100.0} &amp;= \left[\color{steelblue}{e^{{-0.4982}}}, \color{steelblue}{e^{{-0.464}}}, \color{steelblue}{e^{{-0.4525}}}, \color{steelblue}{e^{{-0.473}}}, \color{steelblue}{e^{{-0.4832}}}\color{None}\right] \\
\color{steelblue}e^{x_i/\color{red}100.0} &amp;= \left[\color{steelblue}{0.6076}, \color{steelblue}{0.6288}, \color{steelblue}{0.636}, \color{steelblue}{0.6231}, \color{steelblue}{0.6168}\color{None}\right] \\
\\
\text{The denominator:} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{x_1/\color{red}T}} + \color{purple}{e^{x_2/\color{red}T}} + \color{purple}{e^{x_3/\color{red}T}} + \color{purple}{e^{x_4/\color{red}T}} + \color{purple}{e^{x_5/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}T} &amp;= \color{purple}{e^{-49.82/\color{red}T}} + \color{purple}{e^{-46.4/\color{red}T}} + \color{purple}{e^{-45.25/\color{red}T}} + \color{purple}{e^{-47.3/\color{red}T}} + \color{purple}{e^{-48.32/\color{red}T}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}100.0} &amp;= \color{purple}{e^{-49.82/\color{red}100.0}} + \color{purple}{e^{-46.4/\color{red}100.0}} + \color{purple}{e^{-45.25/\color{red}100.0}} + \color{purple}{e^{-47.3/\color{red}100.0}} + \color{purple}{e^{-48.32/\color{red}100.0}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}100.0} &amp;= \color{purple}{e^{{-0.4982}}} + \color{purple}{e^{{-0.464}}} + \color{purple}{e^{{-0.4525}}} + \color{purple}{e^{{-0.473}}} + \color{purple}{e^{{-0.4832}}} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}100.0} &amp;= \color{purple}{0.6076} + \color{purple}{0.6288} + \color{purple}{0.636} + \color{purple}{0.6231} + \color{purple}{0.6168} \\
\color{purple}\sum_{j=1}^{N=5} e^{x_j/\color{red}100.0} &amp;= \color{purple}3.112 \\
\\
\\
\text{Combine all:} \\
\text{Softmax}(x_{i=1:5},{\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{x_1/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_2/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_3/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_4/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }, \frac{\color{steelblue}e^{x_5/\color{red}T} }            { \color{purple} e^{x_1/\color{red}T} + e^{x_2/\color{red}T} + e^{x_3/\color{red}T} + e^{x_4/\color{red}T} + e^{x_5/\color{red}T}     }\right] \\\\
\text{Softmax}(x, {\color{red}T}) &amp;= \left[\frac{\color{steelblue}e^{-49.82/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-46.4/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-45.25/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-47.3/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }, \frac{\color{steelblue}e^{-48.32/\color{red}T}} {  \color{purple} e^{-49.82/\color{red}T} + e^{-46.4/\color{red}T} + e^{-45.25/\color{red}T} + e^{-47.3/\color{red}T} + e^{-48.32/\color{red}T}    }\right] \\
\\
\text{softmax}(x, {\color{red}100.0}) &amp;= \left[\frac{  \color{steelblue} e^{-49.82/\color{red}100.0}} {  \color{purple} e^{-49.82/\color{red}100.0} + e^{-46.4/\color{red}100.0} + e^{-45.25/\color{red}100.0} + e^{-47.3/\color{red}100.0} + e^{-48.32/\color{red}100.0}    }, \frac{  \color{steelblue} e^{-46.4/\color{red}100.0}} {  \color{purple} e^{-49.82/\color{red}100.0} + e^{-46.4/\color{red}100.0} + e^{-45.25/\color{red}100.0} + e^{-47.3/\color{red}100.0} + e^{-48.32/\color{red}100.0}    }, \frac{  \color{steelblue} e^{-45.25/\color{red}100.0}} {  \color{purple} e^{-49.82/\color{red}100.0} + e^{-46.4/\color{red}100.0} + e^{-45.25/\color{red}100.0} + e^{-47.3/\color{red}100.0} + e^{-48.32/\color{red}100.0}    }, \frac{  \color{steelblue} e^{-47.3/\color{red}100.0}} {  \color{purple} e^{-49.82/\color{red}100.0} + e^{-46.4/\color{red}100.0} + e^{-45.25/\color{red}100.0} + e^{-47.3/\color{red}100.0} + e^{-48.32/\color{red}100.0}    }, \frac{  \color{steelblue} e^{-48.32/\color{red}100.0}} {  \color{purple} e^{-49.82/\color{red}100.0} + e^{-46.4/\color{red}100.0} + e^{-45.25/\color{red}100.0} + e^{-47.3/\color{red}100.0} + e^{-48.32/\color{red}100.0}    }\right] \\
\\
\text{softmax}(x, {\color{red}100.0}) &amp;= \left[\frac{  \color{steelblue}  e^{ -0.4982 }} {  \color{purple} e^{-0.4982 } + e^{-0.464 } + e^{-0.4525 } + e^{-0.473 } + e^{-0.4832 }    }, \frac{  \color{steelblue}  e^{ -0.464 }} {  \color{purple} e^{-0.4982 } + e^{-0.464 } + e^{-0.4525 } + e^{-0.473 } + e^{-0.4832 }    }, \frac{  \color{steelblue}  e^{ -0.4525 }} {  \color{purple} e^{-0.4982 } + e^{-0.464 } + e^{-0.4525 } + e^{-0.473 } + e^{-0.4832 }    }, \frac{  \color{steelblue}  e^{ -0.473 }} {  \color{purple} e^{-0.4982 } + e^{-0.464 } + e^{-0.4525 } + e^{-0.473 } + e^{-0.4832 }    }, \frac{  \color{steelblue}  e^{ -0.4832 }} {  \color{purple} e^{-0.4982 } + e^{-0.464 } + e^{-0.4525 } + e^{-0.473 } + e^{-0.4832 }    }\right] \\
\\
\text{softmax}(x, {\color{red}100.0}) &amp;= \left[\frac{ \color{steelblue}  { 0.6076 } } {  \color{purple} 0.6076 + 0.6288 + 0.636 + 0.6231 + 0.6168    }, \frac{ \color{steelblue}  { 0.6288 } } {  \color{purple} 0.6076 + 0.6288 + 0.636 + 0.6231 + 0.6168    }, \frac{ \color{steelblue}  { 0.636 } } {  \color{purple} 0.6076 + 0.6288 + 0.636 + 0.6231 + 0.6168    }, \frac{ \color{steelblue}  { 0.6231 } } {  \color{purple} 0.6076 + 0.6288 + 0.636 + 0.6231 + 0.6168    }, \frac{ \color{steelblue}  { 0.6168 } } {  \color{purple} 0.6076 + 0.6288 + 0.636 + 0.6231 + 0.6168    }\right] \\
\\
\text{softmax}(x, {\color{red}100.0}) &amp;= \left[\frac{ \color{steelblue}{ 0.6076 } } {  \color{purple} 3.112    }, \frac{ \color{steelblue}{ 0.6288 } } {  \color{purple} 3.112    }, \frac{ \color{steelblue}{ 0.636 } } {  \color{purple} 3.112    }, \frac{ \color{steelblue}{ 0.6231 } } {  \color{purple} 3.112    }, \frac{ \color{steelblue}{ 0.6168 } } {  \color{purple} 3.112    }\right] \\
\\
\\
\text{softmax}(x, {\color{red}100.0})&amp;= [0.1952, 0.202, 0.2044, 0.2002, 0.1982] \
\\
\text{Probabilities}&amp;= [0.1952, 0.202, 0.2044, 0.2002, 0.1982]
\end{align}\)</span></p>
</div>
</div>
<p><strong>Using Python:</strong></p>
<div id="cell-36" class="cell" data-execution_count="325">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example Softmax Calculation</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume for simplicity:</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># * The model only knows the 5 words listed below (it has a vocabulary of 5).</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Example model output</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>model_output_vals <span class="op">=</span> {<span class="st">"word_index"</span>:[i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>)],</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>                <span class="st">"words"</span>:[<span class="st">"ceiling"</span>, <span class="st">"floor"</span>, <span class="st">"mat"</span>, <span class="st">"car"</span>, <span class="st">"grass"</span>], </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>                <span class="st">"logits"</span>:[<span class="op">-</span><span class="fl">49.82</span>, <span class="op">-</span><span class="fl">46.40</span>, <span class="op">-</span><span class="fl">45.25</span>, <span class="op">-</span><span class="fl">47.30</span>, <span class="op">-</span><span class="fl">48.32</span>]}</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> <span class="fl">100.0</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert the data to a DataFrame</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>model_output <span class="op">=</span> pd.DataFrame(model_output_vals)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Define a softmax function with temperature</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> my_softmax(input_vector, Temp<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.exp(np.divide(input_vector,Temp))</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> e <span class="op">/</span> e.<span class="bu">sum</span>()</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate the probabilities</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span>  my_softmax(model_output[<span class="st">"logits"</span>], Temp<span class="op">=</span>temp)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>model_output[<span class="st">"softmax_prob"</span>] <span class="op">=</span> probs </span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="co">#Select the most probable word</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>most_prob <span class="op">=</span> np.argmax(probs)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The index of the most probable word is: </span><span class="sc">{</span>most_prob<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="co">#Pull out the most probable word</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The most probable word is: </span><span class="sc">{</span> model_output[<span class="st">'words'</span>][most_prob] <span class="sc">}</span><span class="ss">"</span> \</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f" (Prob: </span><span class="sc">{</span>model_output[<span class="st">'softmax_prob'</span>][most_prob]<span class="sc">:.5f}</span><span class="ss">)"</span>)</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a><span class="co">#Style our table</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>cm <span class="op">=</span> sns.light_palette(<span class="st">"orange"</span>, as_cmap<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>s1 <span class="op">=</span> model_output</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>s1 <span class="op">=</span> s1.style.background_gradient(subset<span class="op">=</span>[<span class="st">"logits"</span>],cmap<span class="op">=</span>cm)</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>cm <span class="op">=</span> sns.light_palette(<span class="st">"green"</span>, as_cmap<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>s1.background_gradient(subset<span class="op">=</span>[<span class="st">"softmax_prob"</span>],cmap<span class="op">=</span>cm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
The index of the most probable word is: 2

The most probable word is: mat (Prob: 0.20436)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="325">
<style type="text/css">
#T_16a11_row0_col2 {
  background-color: #f3f0ee;
  color: #000000;
}
#T_16a11_row0_col3 {
  background-color: #ebf3eb;
  color: #000000;
}
#T_16a11_row1_col2 {
  background-color: #fcb83c;
  color: #000000;
}
#T_16a11_row1_col3 {
  background-color: #3c9d3c;
  color: #f1f1f1;
}
#T_16a11_row2_col2 {
  background-color: #ffa500;
  color: #000000;
}
#T_16a11_row2_col3 {
  background-color: #008000;
  color: #f1f1f1;
}
#T_16a11_row3_col2 {
  background-color: #fac76b;
  color: #000000;
}
#T_16a11_row3_col3 {
  background-color: #6bb46b;
  color: #f1f1f1;
}
#T_16a11_row4_col2 {
  background-color: #f7d7a0;
  color: #000000;
}
#T_16a11_row4_col3 {
  background-color: #9fce9f;
  color: #000000;
}
</style>

<table id="T_16a11" data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_16a11_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">word_index</th>
<th id="T_16a11_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">words</th>
<th id="T_16a11_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">logits</th>
<th id="T_16a11_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">softmax_prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_16a11_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">0</td>
<td id="T_16a11_row0_col0" class="data row0 col0">0</td>
<td id="T_16a11_row0_col1" class="data row0 col1">ceiling</td>
<td id="T_16a11_row0_col2" class="data row0 col2">-49.820000</td>
<td id="T_16a11_row0_col3" class="data row0 col3">0.195229</td>
</tr>
<tr class="even">
<td id="T_16a11_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">1</td>
<td id="T_16a11_row1_col0" class="data row1 col0">1</td>
<td id="T_16a11_row1_col1" class="data row1 col1">floor</td>
<td id="T_16a11_row1_col2" class="data row1 col2">-46.400000</td>
<td id="T_16a11_row1_col3" class="data row1 col3">0.202022</td>
</tr>
<tr class="odd">
<td id="T_16a11_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">2</td>
<td id="T_16a11_row2_col0" class="data row2 col0">2</td>
<td id="T_16a11_row2_col1" class="data row2 col1">mat</td>
<td id="T_16a11_row2_col2" class="data row2 col2">-45.250000</td>
<td id="T_16a11_row2_col3" class="data row2 col3">0.204358</td>
</tr>
<tr class="even">
<td id="T_16a11_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">3</td>
<td id="T_16a11_row3_col0" class="data row3 col0">3</td>
<td id="T_16a11_row3_col1" class="data row3 col1">car</td>
<td id="T_16a11_row3_col2" class="data row3 col2">-47.300000</td>
<td id="T_16a11_row3_col3" class="data row3 col3">0.200211</td>
</tr>
<tr class="odd">
<td id="T_16a11_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">4</td>
<td id="T_16a11_row4_col0" class="data row4 col0">4</td>
<td id="T_16a11_row4_col1" class="data row4 col1">grass</td>
<td id="T_16a11_row4_col2" class="data row4 col2">-48.320000</td>
<td id="T_16a11_row4_col3" class="data row4 col3">0.198180</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-37" class="cell" data-execution_count="385">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the softmax probabilities we see that the most probable word is: <span style="color: green; font-weight: bold">mat</span> with a probability of : <span style="color: green; font-weight: bold">0.666</span></p>
</details>
<details>
<summary>
<strong>What does this mean?</strong>
</summary>
<p>Between the temperature values of <strong>1.0</strong> and <strong>100.0</strong> we see that the probability distribution goes from being <strong>more ‘peaky’</strong> to <strong>more ‘flat’</strong> or uniform. This means that words that would have a low chance of being chosen when the temperature is low would now have a higher chance of being chosen. </p>
<p>Since we’re using <strong>greedy sampling</strong>, the word with the highest probability always gets select, but if we change our method to randomly pick a word from the top 3 probabilites, the possible choices become: <strong>[‘mat’ ‘floor’ ‘car’]</strong></p>
</details>
<p><br></p>
</details></section>
</section>
</section>
<section id="llm-with-temperature-applied" class="level3">
<h3 class="anchored" data-anchor-id="llm-with-temperature-applied">LLM with Temperature Applied</h3>
<p>To see how the temperature parameter affects the LLM outputs we’ll use the <a href="https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf">GPT-2 model by OpenAI</a> for text generation. The GPT-2 model is a fairly small, open sourced model that can be accessed and used via <a href="https://huggingface.co/docs/transformers/model_doc/gpt2">Hugging Face</a>.<br> GPT-2 has:</p>
<ul>
<li><p>1.5 billion parameters</p></li>
<li><p>50257 vocabulary size (number of words it knows)</p></li>
<li><p>768 vector embedding size</p></li>
<li><p>12 attention heads</p></li>
<li><p>12 layers</p></li>
</ul>
<p><br> We’ll look at using the LLM for two types of task:</p>
<ul>
<li>Single next word generation</li>
<li>Continuous next word generation</li>
</ul>

<details>
<summary>
<strong>Model Set up</strong>
</summary>
<p>To get the model(<code>gpt2</code>) we download it from Hugging Face and set the model’s task to <code>text-generation</code></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> AutoModelForCausalLM, AutoTokenizer</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>model_to_load <span class="op">=</span> <span class="st">"openai-community/gpt2"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>model_to_load_task <span class="op">=</span> <span class="st">"text-generation"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the model's pretrained tokenizer</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>tokenizer <span class="op">=</span> AutoTokenizer.from_pretrained(model_to_load)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the pretrained model</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> AutoModelForCausalLM.from_pretrained(</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    model_to_load,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    device_map <span class="op">=</span> device, <span class="co">#CPU or GPU</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    torch_dtype <span class="op">=</span> <span class="st">"auto"</span>,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    trust_remote_code <span class="op">=</span> <span class="va">True</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>To pass inputs to the model we can run the following</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Input sentence</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"The cat sat on the"</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Tokenize/encode input prompt</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>input_ids <span class="op">=</span> tokenizer.encode(prompt, return_tensors<span class="op">=</span><span class="st">"pt"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the output with adjusted temperature</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>outputs <span class="op">=</span> model.generate(input_ids,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>                        max_new_tokens<span class="op">=</span><span class="dv">1</span>, <span class="co">#Just want one word generated</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>                        temperature<span class="op">=</span>temperature, <span class="co">#Set temp</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>                        output_scores<span class="op">=</span><span class="va">True</span>, <span class="co">#Output model word scores</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>                        output_logits<span class="op">=</span><span class="va">True</span>, <span class="co">#Outout logits</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>                        return_dict_in_generate<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>                        do_sample<span class="op">=</span><span class="va">True</span>, <span class="co">#Perform sampling for next word</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>                        pad_token_id<span class="op">=</span>tokenizer.eos_token_id)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the generated token ID/next word</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>generated_token_id <span class="op">=</span> outputs.sequences[<span class="dv">0</span>][<span class="op">-</span><span class="dv">1</span>].item()    </span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Decode the generated token ID to a word</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>generated_word <span class="op">=</span> tokenizer.decode([generated_token_id])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>/usr/local/lib/python3.11/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(</code></pre>
</details>
<section id="single-next-word-generation" class="level4">
<h4 class="anchored" data-anchor-id="single-next-word-generation">Single next word generation</h4>
<p>With single next word generation the model is given a sentence and is tasked with predicting the next most likely word.</p>
<p><br> For example: We’ll pass the same sentence we’ve been looking at to the LLM to see what it will output.</p>
<ul>
<li>Input sentence: The cat slept on the ______.</li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"The cat slept on the"</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>temps <span class="op">=</span> [<span class="fl">0.1</span>,  <span class="fl">0.5</span>, <span class="fl">1.</span>, <span class="fl">5.</span>, <span class="fl">10.</span>, <span class="fl">100.</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ii <span class="kw">in</span> temps:</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  word_out <span class="op">=</span> next_word_prediction(prompt, temp<span class="op">=</span>ii)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f"LLM Temperature: </span><span class="sc">{</span>ii<span class="sc">}</span><span class="ss"> </span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>prompt<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>word_out<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here we pass the same input sentence to the LLM with different temperature values and look at the probability distribution of select words in the model’s vocabulary.</p>
<section id="examples-1" class="level5">
<h5 class="anchored" data-anchor-id="examples-1">Examples</h5>
<div id="cell-48" class="cell" data-execution_count="466">
<div class="cell-output cell-output-stdout">
<pre><code>Generated word:  floor         ( token index: 4314,          logit:-82.82,          prob: 0.9891 )
Generated word:  top         ( token index: 1353,          logit:-85.89,          prob: 0.0012 )
Generated word:  bed         ( token index: 3996,          logit:-83.61,          prob: 0.0857 )
Generated word:  rug         ( token index: 14477,          logit:-87.13,          prob: 0.0002 )
Generated word:  back         ( token index: 736,          logit:-85.49,          prob: 0.0001 )
Generated word:  right         ( token index: 826,          logit:-87.17,          prob: 0.0000 )</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>LLM Temperature: 0.1</strong></p>
<p>Input : <span style="color: gray; text-decoration: underline">The cat slept on the </span></p>
<p>Output: <span style="color: gray; text-decoration: underline">The cat slept on the </span> <span style="color: green; text-decoration: underline"> floor</span></p>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-22-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>LLM Temperature: 0.5</strong></p>
<p>Input : <span style="color: gray; text-decoration: underline">The cat slept on the </span></p>
<p>Output: <span style="color: gray; text-decoration: underline">The cat slept on the </span> <span style="color: green; text-decoration: underline"> top</span></p>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-22-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>LLM Temperature: 1.0</strong></p>
<p>Input : <span style="color: gray; text-decoration: underline">The cat slept on the </span></p>
<p>Output: <span style="color: gray; text-decoration: underline">The cat slept on the </span> <span style="color: green; text-decoration: underline"> bed</span></p>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-22-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>LLM Temperature: 5.0</strong></p>
<p>Input : <span style="color: gray; text-decoration: underline">The cat slept on the </span></p>
<p>Output: <span style="color: gray; text-decoration: underline">The cat slept on the </span> <span style="color: green; text-decoration: underline"> rug</span></p>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-22-output-9.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>LLM Temperature: 10.0</strong></p>
<p>Input : <span style="color: gray; text-decoration: underline">The cat slept on the </span></p>
<p>Output: <span style="color: gray; text-decoration: underline">The cat slept on the </span> <span style="color: green; text-decoration: underline"> back</span></p>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-22-output-11.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>LLM Temperature: 100.0</strong></p>
<p>Input : <span style="color: gray; text-decoration: underline">The cat slept on the </span></p>
<p>Output: <span style="color: gray; text-decoration: underline">The cat slept on the </span> <span style="color: green; text-decoration: underline"> right</span></p>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="LLM_temp_files/figure-html/cell-22-output-13.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>What does this mean?</strong></p>
<p>As the temperature increases from 0.1 to 100.0 the output words that were generated, generally all seem plausible.</p>
<p>Looking at the distribution of words we see that going from 0.1 to 100.0 the distribution goes from being very “peaky” around the most likely word to flat across all words.</p>
<p>This demonstrates how the temperature parameter affects the probability distribution of words from the LLM’s vocabulary so that some are more or less likely to be selected as the next generated word in a sequence.</p>
<p><br></p>
</section>
</section>
<section id="continuous-next-word-generation" class="level4">
<h4 class="anchored" data-anchor-id="continuous-next-word-generation">Continuous next word generation</h4>
<p>With continuous next word generation the model is given a sentence and is tasked with predicting the next most likely word in an autoregressive manner. The predicted word is added to the sentence and passed for the next iteration of prediction unit an end of sentence token (<code>&lt;EOS&gt;</code> or <code>\n</code>) is generated or the max number of iterations is reached.</p>
<p><br> We’ll pass the same sentence we’ve been looking at to the LLM to see what it will <span style="color:green"> output </span> over a number of iterations like below.</p>
<ul>
<li>Input sentence: The cat slept on the ______</li>
<li>1: The cat slept on the <span style="color:green">floor</span> ______</li>
<li>2: The cat slept on the floor <span style="color:green">next</span> ______</li>
<li>3: The cat slept on the floor next <span style="color:green">to</span> ______</li>
<li>4: The cat slept on the floor next to <span style="color:green">the</span> ______</li>
<li>5: The cat slept on the floor next to the <span style="color:green">window</span> ______</li>
<li>6: The cat slept on the floor next to the window <span style="color:green">.</span> ______</li>
<li>7: The cat slept on the floor next to the window . <span style="color:green">&lt; EOS &gt;</span></li>
</ul>
<p>We’ll pass the <code>prompt</code> to the LLM and append its predicted output (<code>word_out</code>) to the prompt and keep iterating until we reach the max number of iterations (<code>max_gen_iteration</code>) or and end of sentence token (<code>&lt;EOS&gt;</code> or <code>\n</code>) is predicted.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"The cat slept on the"</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>max_gen_iteration <span class="op">=</span> <span class="dv">15</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ii <span class="kw">in</span> <span class="bu">range</span>(max_gen_iteration):</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  word_out, probs_out <span class="op">=</span> next_word_prediction(prompt, temp<span class="op">=</span>temp)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(prompt <span class="op">+</span> word_out)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  prompt <span class="op">+=</span> word_out</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here we pass the same input sentence to the LLM with different temperature values and look at the probability distribution of select words in the model’s vocabulary.</p>
<section id="examples-2" class="level5">
<h5 class="anchored" data-anchor-id="examples-2">Examples</h5>
<details>
<summary>
<strong>Temp: 0.5</strong>
</summary>
<p>Parameters:</p>
<ul>
<li>Input text: “The cat slept on the”</li>
<li>Temperature: 0.5</li>
<li>Max iterations: 20</li>
</ul>
<div id="cell-53" class="cell" data-execution_count="488">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"The cat slept on the"</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>max_iter <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>gen_next_word_loop(prompt, temp <span class="op">=</span> temp, max_iter <span class="op">=</span> max_iter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the</span><span style="color: green; text-decoration: underline"> floor</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor</span><span style="color: green; text-decoration: underline"> of</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of</span><span style="color: green; text-decoration: underline"> the</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the</span><span style="color: green; text-decoration: underline"> cabin</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin</span><span style="color: green; text-decoration: underline"> for</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for</span><span style="color: green; text-decoration: underline"> a</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a</span><span style="color: green; text-decoration: underline"> few</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few</span><span style="color: green; text-decoration: underline"> hours</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours</span><span style="color: green; text-decoration: underline"> before</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before</span><span style="color: green; text-decoration: underline"> it</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before it</span><span style="color: green; text-decoration: underline"> was</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before it was</span><span style="color: green; text-decoration: underline"> taken</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before it was taken</span><span style="color: green; text-decoration: underline"> to</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before it was taken to</span><span style="color: green; text-decoration: underline"> the</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before it was taken to the</span><span style="color: green; text-decoration: underline"> shelter</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before it was taken to the shelter</span><span style="color: green; text-decoration: underline">.</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the floor of the cabin for a few hours before it was taken to the shelter.</span><span style="color: green; text-decoration: underline"> </span></p>
</div>
</div>
</details>
<details>
<summary>
<strong>Temp: 2.0</strong>
</summary>
<p>Parameters:</p>
<ul>
<li>Input text: “The cat slept on the”</li>
<li>Temperature: 2.0</li>
<li>Max iterations: 20</li>
</ul>
<div id="cell-55" class="cell" data-execution_count="490">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"The cat slept on the"</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> <span class="fl">2.0</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>max_iter <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>gen_next_word_loop(prompt, temp <span class="op">=</span> temp, max_iter <span class="op">=</span> max_iter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the</span><span style="color: green; text-decoration: underline"> inside</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside</span><span style="color: green; text-decoration: underline">,</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside,</span><span style="color: green; text-decoration: underline"> trying</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying</span><span style="color: green; text-decoration: underline"> the</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the</span><span style="color: green; text-decoration: underline"> inside</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside</span><span style="color: green; text-decoration: underline">-</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-</span><span style="color: green; text-decoration: underline">out</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out</span><span style="color: green; text-decoration: underline"> of</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of</span><span style="color: green; text-decoration: underline"> these</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these</span><span style="color: green; text-decoration: underline"> chairs</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs</span><span style="color: green; text-decoration: underline">.</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs.</span><span style="color: green; text-decoration: underline"> She</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She</span><span style="color: green; text-decoration: underline"> was</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She was</span><span style="color: green; text-decoration: underline"> being</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She was being</span><span style="color: green; text-decoration: underline"> fed</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She was being fed</span><span style="color: green; text-decoration: underline"> from</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She was being fed from</span><span style="color: green; text-decoration: underline"> one</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She was being fed from one</span><span style="color: green; text-decoration: underline">,</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She was being fed from one,</span><span style="color: green; text-decoration: underline"> her</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the inside, trying the inside-out of these chairs. She was being fed from one, her</span><span style="color: green; text-decoration: underline"> two</span></p>
</div>
</div>
</details>
<details>
<summary>
<strong>Temp: 10.0</strong>
</summary>
<p>Parameters:</p>
<ul>
<li>Input text: “The cat slept on the”</li>
<li>Temperature: 10.0</li>
<li>Max iterations: 20</li>
</ul>
<div id="cell-57" class="cell" data-execution_count="491">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"The cat slept on the"</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> <span class="fl">10.0</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>max_iter <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>gen_next_word_loop(prompt, temp <span class="op">=</span> temp, max_iter <span class="op">=</span> max_iter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the</span><span style="color: green; text-decoration: underline"> left</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left</span><span style="color: green; text-decoration: underline"> one</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one</span><span style="color: green; text-decoration: underline"> piece</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece</span><span style="color: green; text-decoration: underline"> side</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side</span><span style="color: green; text-decoration: underline"> at</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at</span><span style="color: green; text-decoration: underline"> day</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day</span><span style="color: green; text-decoration: underline"> one</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one</span><span style="color: green; text-decoration: underline">!</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one!</span><span style="color: green; text-decoration: underline"> [</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [</span><span style="color: green; text-decoration: underline">laughs</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs</span><span style="color: green; text-decoration: underline"> about</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about</span><span style="color: green; text-decoration: underline"> how</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how</span><span style="color: green; text-decoration: underline"> long</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how long</span><span style="color: green; text-decoration: underline"> they</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how long they</span><span style="color: green; text-decoration: underline"> both</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how long they both</span><span style="color: green; text-decoration: underline"> would</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how long they both would</span><span style="color: green; text-decoration: underline"> lie</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how long they both would lie</span><span style="color: green; text-decoration: underline"> still</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how long they both would lie still</span><span style="color: green; text-decoration: underline"> at</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span style="color: gray; text-decoration: underline">The cat slept on the left one piece side at day one! [laughs about how long they both would lie still at</span><span style="color: green; text-decoration: underline"> sunrise</span></p>
</div>
</div>
</details>
<p><strong>What does this mean?</strong></p>
<p>If we look at the outputs between a temperature of 0.5 vs 10.0, we see that at a temperature of 0.5 the output text is more coherent whereas for a temperature of 10.0 the output is more incoherent and does not make sense to a human reader.</p>
<p>This demonstrates how the temperature parameter can influence the next generated word by adjusting the probability distribution of words within the LLM’s vocabulary.</p>
</section>
</section>
</section>
</section>
<section id="take-away" class="level2">
<h2 class="anchored" data-anchor-id="take-away">Take Away</h2>
<p>The temperature parameter in LLMs controls the randomness of generated text where lower values produce more coherent and deterministic outputs whereas higher values produce more diverse and sometimes incoherent outputs.</p>
<p>Ongoing work has examined the use of dynamically tuning temperature with inputs to improve generation quality and diversity. With these advancements to the use of temperature, we can expect to see better LLM generation capabilities across a range of tasks.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>