---
title: "Publications"


---

For the latest publications see [Google Scholar](https://scholar.google.com/citations?user=ys2YCxIAAAAJ&hl=en)


## Papers


|Title| Year |
-----------------------------------------|-----:
|**A Scalable Framework for Closed-Loop Neuromodulation with Deep Learning.** N. Gebodh, V. Miskovic, S. Laszlo, A. Datta, M. Bikson, 2023.  bioRxiv, pp.2023-01. doi:[10.1101/2023.01.18.524615](https://doi.org/10.1101%2F2023.01.18.524615) | 2023 [PDF](https://www.biorxiv.org/content/10.1101/2023.01.18.524615v1.full.pdf)
|**Novel Evoked Synaptic Activity Potentials (ESAPs) Elicited by Spinal Cord Stimulation.** M. Sharma, V. Bhaskar,L. Yang,M. FallahRad, N. Gebodh, T. Zhang, R. Esteller, J. Martin, M. Bikson, 2023.  Eneuro, 10(5). doi:[10.1523/ENEURO.0429-22.2023](https://doi.org/10.1523/ENEURO.0429-22.2023)| 2023 [PDF](https://www.eneuro.org/content/eneuro/10/5/ENEURO.0429-22.2023.full.pdf)
|**Dataset of concurrent EEG, ECG, and behavior with multiple doses of transcranial electrical stimulation.** N. Gebodh, Z. Esmaeilpour, A. Datta, M. Bikson (2021) Nature Scientific Data 8:274. doi:[10.1038/s41597-021-01046-y](https://doi.org/10.1038/s41597-021-01046-y)    | 2021 [PDF](https://www.nature.com/articles/s41597-021-01046-y.pdf)
|**Electrical stimulation of cranial nerves in cognition and disease.** D. Adair, D. Truong, Z. Esmaeilpour, N. Gebodh H. Borges, L. Ho, J D. Bremner, B. W Badran, V. Napadow, V. P Clark, M. Bikson.  Brain stimulation. (13). pp. 717-750. 23 February 2020, doi:[10.1016/j.brs.2020.02.019](https://doi.org/10.1016/j.brs.2020.02.019)  | 2020 [PDF](https://www.sciencedirect.com/science/article/pii/S1935861X20300413/pdfft?md5=534694d19cce4283d952af63a38515de&pid=1-s2.0-S1935861X20300413-main.pdf)
|**Experimental-design Specific Changes in Spontaneous EEG and During Intermittent Photic Stimulation by High Definition Transcranial Direct Current Stimulation.** V.V. Lazarev, N. Gebodh, T. Tamborino, M. Bikson, E.M. Caparelli-Daquer.  Neuroscience 2020;426:50–8. doi:[10.1016/j.neuroscience.2019.11.016](https://doi.org/10.1016/j.neuroscience.2019.11.016) | 2020 [PDF](https://nonagon-grouper-x4a7.squarespace.com/s/Experimental-design-Specific-Changes-in-Spontaneous-EEG-and-During-Intermittent-Photic-Stimulation-b.pdf)
|**Inherent physiological artifacts in EEG during tDCS.** N. Gebodh, Z. Esmaeilpour, D. Adair, K. Chelette, J. Dmochowski, A.J. Woods, E.S. Kappenman, L.C. Parra, M. Bikson.  NeuroImage. (185). pp. 408-424. 15 January 2019, doi:[10.1016/j.neuroimage.2018.10.025](https://doi.org/10.1016/j.neuroimage.2018.10.025) | 2019 [PDF](./papers/Gebodh_2019_EEG_artifacts.pdf)
|**Antiepileptic Effects of a Novel Non-invasive Neuromodulation Treatment in a Subject With Early-Onset Epileptic Encephalopathy: Case Report With 20 Sessions of HD-tDCS Intervention.** O. Meiron, R. Gale, J. Namestnic, O. Bennet-Back, N. Gebodh, Z. Esmaeilpour, V. Mandzhiyev, M. Bikson.  Front. Neurosci. 13:547. 2019. doi:[10.3389/fnins.2019.00547](https://doi.org/10.3389/fnins.2019.00547) | 2019 [PDF](./papers/Merion_2019_HDtDCS_Epilepsy.pdf)
|**Effects of stimulus size and contrast on the initial primary visual cortical response in humans.** N. Gebodh, M I. Vanegas, S. P Kelly. Effects of stimulus size and contrast on the initial primary visual cortical response in humans. Brain Topography. 2017 Jul;30(4):450-60. doi:[10.1007/s10548-016-0530-2](https://doi.org/10.1007/s10548-016-0530-2) | 2017 [PDF](./papers/Gebodh_2017_EffectsStimSizeContrastOnV1_C1.pdf)
| **Clinically Effective Treatment of Fibromyalgia Pain With High-Definition Transcranial Direct Current Stimulation: Phase II Open-Label Dose Optimization.** L. Castillo-Saavedra and N. Gebodh, M. Bikson, C. Diaz-Cruz, R. Brandao, L. Coutinho, D. Truong, A. Datta, R. Shani-Hershkovich, M. Weiss, I. Laufer, A. Reches, Z. Peremen, A. Geva, L.C. Parra, F. Fregni.  J Pain. 2016 17(1):14-26. doi:[10.1016/j.jpain.2015.09.009](https://doi.org/10.1016/j.jpain.2015.09.009) | 2016 [PDF](https://www.sciencedirect.com/science/article/pii/S1526590015008846/pdfft?md5=41b1687d35f28db7b422834211180699&pid=1-s2.0-S1526590015008846-main.pdf)


## Book Chapters

|Title| Year |
---------------------------------------------|-----:
|**Transcranial direct current stimulation among technologies for low-intensity transcranial electrical stimulation: classification, history, and terminology in Practical guide to transcranial direct current stimulation.** N. Gebodh, Z. Esmaeilpour, D. Adair, P. Schestattsky, F. Fregni, M. Bikson. Springer, Cham  – 2019, Chapter 1, Page 3-43. doi:[https://doi.org/10.1007/978-3-319-95948-1_1](https://doi.org/10.1007/978-3-319-95948-1_1) | 2019
|**Transcranial direct current stimulation integration with magnetic resonance imaging, magnetic resonance spectroscopy, near infrared spectroscopy imaging, and electroencephalography in Practical guide to transcranial direct current stimulation.** A. J Woods, M. Bikson, K. Chelette, J. Dmochowski, A. Dutta, Z. Esmaeilpour, N. Gebodh, M. A Nitsche, C. Stagg.  Springer, Cham  – 2019, Chapter 11, Page 293-345. doi:[https://doi.org/10.1007/978-3-319-95948-1_11](https://doi.org/10.1007/978-3-319-95948-1_11) | 2019
|**Transcranial Electrical Stimulation: transcranial Direct Current Stimulation (tDCS), transcranial Alternating Current Stimulation (tACS), transcranial Pulsed Current Stimulation (tPCS), and Transcranial Random Noise Stimulaiton (tRNS) in The Stimulated Brain.** I. Moreno-Duarte, N. Gebodh, P. Schestatsky, B. Guleyupoglu, D. Reato, M. Bikson, F. Fregni.(Cohen Kadosh ed.) Elsevier Science – 2014, Chapter 2, Page 35-60. doi:[https://doi.org/10.1016/B978-0-12-404704-4.00002-8](https://doi.org/10.1016/B978-0-12-404704-4.00002-8) | 2014

## Research Presentations

* Gebodh N, Datta A, Bikson M. A Machine Learning Framework of Closed-loop Neuromodulation Applied to Sustained Attentional Enhancement. Poster session presented at Military Health System Research Symposium; 2022 Sep 12- 15; Kissimmee, FL. 

* Gebodh N, Miskovic V, Laszlo S, Datta A, Bikson M. Deep learning framework for non-invasive closed-loop neuromodulation for attention. Poster session presented at Neuroergonomics & NYC Neuromodulation; 2022 Jul 28- Aug 1; New York, NY. 

* Sharma M, Bhaskar V, Yang L, Gebodh N, FallahRad M, Zhang T, Esteller R, Martin J, Bikson M.  Evoked Synaptic Excitatory Potentials (ESAPs): A novel electrophysiological biomarker for Spinal Cord Stimulation. Poster session presented at Neuroergonomics & NYC Neuromodulation; 2022 Jul 28- Aug 1; New York, NY. 

* Gebodh N, Bikson M. A Machine Learning Based Closed-Loop Neuromodulation Framework.  Poster session presented at The International Neuromodulation Society; 2022 May 21-26; Barcelona, Spain. Doi: https://doi.org/10.1016/j.neurom.2022.08.002

* Gebodh N, Esmaeilpour Z, Datta A, Bikson M. A novel approach to closed-loop neuromodulation with machine learning. Poster session presented at 4th International Brain  Stimulation Conference; 2021 Dec 7-10;Charleston,South Carolina. Doi: https://doi.org/10.1016/j.brs.2021.10.235

* Gebodh N, Esmaeilpour Z, Datta A, Bikson M. A large open source neuromodulation dataset of concurrent EEG, ECG, behavior, and transcranial electrical stimulation. Poster session presented at 4th International Brain  Stimulation Conference; 2021 Dec 7-10;Charleston,South Carolina. Doi: https://doi.org/10.1016/j.brs.2021.10.108  

* Gebodh N, Vacchi L, Adair D, Esmaeilpour Z, Poltorak A, Poltorak V, Bikson M. Modulation of Sleepiness and Physiology with Brain-Derived and Narrow-Band tACS. Poster session presented at 2019 Neuromodulation: The Science and NYC Neuromodulation Joint Meeting; 2019 Oct 2-5; Napa, California.  

* Vacchi L, Gebodh N, Adair D, Unal G, Poltorak A,  Poltorak V, Bikson M. Transcranial Endogenous Sleep-Derived waveform to induce sleepiness. Poster session presented at The Annual Meeting of Milan Center for Neuroscience; 2018 Nov 21; Milan, Italy.

* Gebodh N, Adair D, Esmaeilpour Z, Chelette K, Dmochowski J, Woods A, Kappenman E, Bikson M. Failure of Conventional Signal Processing Techniques to Remove “Physiological” Artifacts from EEG During tDCS. Poster session presented at 2018 NYC Neuromodulation Conference and NANS Summer Series; 2018 Aug 24-26; New York, NY.  

* Meiron O, Gale R, Namestnic J, Bennet-Back O, David J, Gebodh N, Adair D, Esmaeilpour Z, Bikson M. Attenuation of pathological EEG features in nonatal electroclinical syndromes: HD-tDCS in catastrophic epilepsies. Poster session presented at Brain Stimulation: Basic, Translational, and Clinical Research in Neuromodulation; 2018 Aug 24-26; New York, NY.

* Gebodh N, Vacchi L, Adair D, Unal G, Poltorak A,  Poltorak V, Bikson M. Replay of endogenous sleep rhythms to produce sleepiness. Poster session presented at 2018 NYC Neuromodulation Conference and NANS Summer Series; 2018 Aug 24-26; New York, NY. Doi: https://doi.org/10.1016/j.brs.2018.12.180  

* Gebodh N, Adair D, Esmaeilpour Z, Chelette K, Dmochowski J, Woods A, Kappenman E, Bikson M. Physiologic artifacts when combining EEG and tDCS. Poster session presented at 2nd International Brain  Stimulation Conference; 2017 Mar 5-8; Barcelona, Spain.  

* Gebodh N, Adair D, Esmaeilpour Z, Chelette K, Dmochowski J, Woods A, Kappenman E, Bikson M. Modulation of physiologic artifacts during concurrent tDCS and EEG. Poster session presented at 6th International Conference on Transcranial Brain Stimulation; 2016 Sept 7-10; Gottingen, DE.  

* Gebodh N, Castillo L, Truong D, Bikson M, Shani-Hershkovich R, Weiss M, Laufer I, Reches A, Peremen Z, Geva A, Parra LC, and Fregni F. Clinically effective treatment of fibromyalgia pain with HD-tDCS – Phase II open-label dose-optimization. Poster session presented at Military Health Research Systems Symposium; 2015 Aug. 16-21; Ft. Lauderdale, FL. 

* Gebodh N, Vanegas I, Kelly S. Characterization of the effects of stimulus size and contrast on the initial afferent response in human primary visual cortex. Poster session presented at Society for Neuroscience; 2014 Nov. 15-19; Washington DC.  

* Vanegas I, Blangero A, Gebodh N, Ali A, Kelly S. Task-dependent attentional modulation of initial afferent activity in human primary visual cortex. Poster session presented at Society for Neuroscience; 2014 Nov. 15-19; Washington DC. 



## Ad Hoc Review

* Brain Stimulation   
* Sleep Medicine     
* PLOS Comp Bio    
* J.NeuroEng & Rehab
* NeuroImage
* Neuropsychologia
* Applied Intelligence 
* Psychophysiology
* Hemodialysis Intl
